### ISSUE TITLE
npm run dev 后打开的页面404

### ISSUE THREAD

**Issue by FisherMS** [EvilChan/vite-chrome-extension-template#1]
是我有什么地方没有配置对吗？

**Comment by EvilChan** [comment]
> 是我有什么地方没有配置对吗？

这个并不是常规的开发，你需要配合浏览器的扩展使用，加载dist目录，https://zhuanlan.zhihu.com/p/628015223

**Comment by EvilChan** [comment]
如果需要正常的开发，在manifest.ts文件中，option_ui的page：src/entries/options/index.html，可以使用http://localhost:9999/src/entries/options/index.html 来访问
